from tkinter import *
import os
from tkinter import ttk
from tkinter import messagebox
from tkinter.ttk import Combobox
from Description import *
from datetime import datetime
import mysql.connector as c
def Book():
    a=Name.get()
    b=People.get()
    c=Kind.get()
    d=Preferred.get()
    e=Days.get()
    if c=="Single":
        i=("UPDATE single SET Occupancy='Occupied', Name=%s, People=%s, Days=%s WHERE Number=%s")
        con.execute(i,(a,b,e,d))
        mydb.commit()
        window=Tk()
        window.geometry("400x150")
        window.title("Booking Status")
        window.configure(background="#add8e6")
        s1=Label(window, text="Your room has been booked!!!\n Have a great stay!!!",fg="#000000",bg="#add8e6",font="Times 18 bold italic")
        s2=Button(window,text="Okay",command=window.destroy, font=(14),bg="#ffffff")
        s1.pack()
        s2.pack()
    elif c=="Double":
        i=("UPDATE two SET Occupancy='Occupied', Name=%s, People=%s, Days=%s WHERE Number=%s")
        con.execute(i,(a,b,e,d))
        mydb.commit()
        window=Tk()
        window.geometry("400x150")
        window.title("Booking Status")
        window.configure(background="#add8e6")
        s1=Label(window, text="Your room has been booked!!!\n Have a great stay!!!",fg="#000000",bg="#add8e6",font="Times 18 bold italic")
        s2=Button(window,text="Okay",command=window.destroy, font=(14),bg="#ffffff")
        s1.pack()
        s2.pack()
    elif c=="Triple":
        i=("UPDATE three SET Occupancy='Occupied', Name=%s, People=%s, Days=%s WHERE Number=%s")
        con.execute(i,(a,b,e,d))
        mydb.commit()
        window=Tk()
        window.geometry("400x150")
        window.title("Booking Status")
        window.configure(background="#add8e6")
        s1=Label(window, text="Your room has been booked!!!\n Have a great stay!!!",fg="#000000",bg="#add8e6",font="Times 18 bold italic")
        s2=Button(window,text="Okay",command=window.destroy, font=(14),bg="#ffffff")
        s1.pack()
        s2.pack()
    elif c=="Queen":
        i=("UPDATE queen SET Occupancy='Occupied', Name=%s, People=%s, Days=%s WHERE Number=%s")
        con.execute(i,(a,b,e,d))
        mydb.commit()
        window=Tk()
        window.geometry("400x150")
        window.title("Booking Status")
        window.configure(background="#add8e6")
        s1=Label(window, text="Your room has been booked!!!\n Have a great stay!!!",fg="#000000",bg="#add8e6",font="Times 18 bold italic")
        s2=Button(window,text="Okay",command=window.destroy, font=(14),bg="#ffffff")
        s1.pack()
        s2.pack()
    elif c=="Suite":
        i=("UPDATE suite SET Occupancy='Occupied', Name=%s, People=%s, Days=%s WHERE Number=%s")
        con.execute(i,(a,b,e,d))
        mydb.commit()
        window=Tk()
        window.geometry("400x150")
        window.title("Booking Status")
        window.configure(background="#add8e6")
        s1=Label(window, text="Your room has been booked!!!\n Have a great stay!!!",fg="#000000",bg="#add8e6",font="Times 18 bold italic")
        s2=Button(window,text="Okay",command=window.destroy, font=(14),bg="#ffffff")
        s1.pack()
        s2.pack()
    else:
        i=("UPDATE presidentsuite SET Occupancy='Occupied', Name=%s, People=%s, Days=%s WHERE Number=%s")
        con.execute(i,(a,b,e,d))
        mydb.commit()
        window=Tk()
        window.geometry("400x150")
        window.title("Booking Status")
        window.configure(background="#add8e6")
        s1=Label(window, text="Your room has been booked!!!\n Have a great stay!!!",fg="#000000",bg="#add8e6",font="Times 18 bold italic")
        s2=Button(window,text="Okay",command=window.destroy, font=(14),bg="#ffffff")
        s1.pack()
        s2.pack()
            
def Billing():
    f=Days.get()
    e=Preferred.get()
    d=Kind.get()
    if d=="Single":
        a="SELECT Occupancy from single WHERE Number=%s"
        con.execute(a,(e,))
        k=con.fetchall()
        if k==[('Vacant',)]:
            if (int(e)>=1 and int(e)<=9):
                dow=Tk()
                dow.geometry("350x300")
                cost=2000
                l1=Label(dow,text="Cost of each room:-",font="Arial 10 bold")
                l2=Label(dow,text="Days of stay:-",font="Arial 10 bold")
                l3=Label(dow,text="Central Goods and Service Tax(CGST):-",font="Arial 10 bold")
                l4=Label(dow,text="State Goods and Service Tax(SGST):-",font="Arial 10 bold")
                l5=Label(dow,text="Total Payable Amount:-",font="Arial 10 bold")
                l6=Label(dow,text=datetime.now().time(),font="Arial 8 bold")
                l7=Label(dow,text=datetime.now().date(),font="Arial 8 bold")
                am=int(f)*2000
                gst=2*(0.18)*2000
                amount=am+gst
                e1=Label(dow,text="2000",font="none 8 bold")
                e2=Label(dow,text=int(f),font="none 8 bold")
                e3=Label(dow,text="18%",font="none 8 bold")
                e4=Label(dow,text="18%",font="none 8 bold")
                e5=Label(dow,text=amount,font="none 8 bold")
                l6.grid(row=0,column=0,padx=5,pady=5)
                l7.grid(row=0,column=1,padx=5,pady=5)
                l1.grid(row=1,column=0,padx=5,pady=5,sticky=W)
                e1.grid(row=1,column=1,padx=5,pady=5,sticky=E)
                l2.grid(row=4,column=0,padx=5,pady=5,sticky=W)
                e2.grid(row=4,column=1,padx=5,pady=5,sticky=E)
                l3.grid(row=8,column=0,padx=5,pady=5,sticky=W)
                e3.grid(row=8,column=1,padx=5,pady=5,sticky=E)
                l4.grid(row=12,column=0,padx=5,pady=5,sticky=W)
                e4.grid(row=12,column=1,padx=5,pady=5,sticky=E)
                l5.grid(row=16,column=0,padx=5,pady=5,sticky=W)
                e5.grid(row=16,column=1,padx=5,pady=5,sticky=E)
                b1=Button(dow,text="Proceed to Pay",command=Pay,font="Arial",bg="#add8e6")
                b2=Button(dow,text="Cancel",command=dow.destroy,font="Arial",bg="#add8e6")
                b1.grid(row=20,column=0,padx=5,pady=5,sticky=W)
                b2.grid(row=20,column=1,padx=5,pady=5,sticky=E)
            else:
                cow=Tk()
                cow.geometry("250x100")
                l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
                l1.grid(row=0,column=0)
                b="SELECT Number FROM Single WHERE Occupancy='Vacant'"
                con.execute(b)
                c=con.fetchall()
                l2=Label(cow,text=c,font="Times 10 bold")
                l2.grid(row=2,column=0)
                b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
                b1.grid(row=4,column=0)
        else:
            cow=Tk()
            cow.geometry("250x100")
            l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
            l1.grid(row=0,column=0)
            b="SELECT Number FROM Single WHERE Occupancy='Vacant'"
            con.execute(b)
            c=con.fetchall()
            l2=Label(cow,text=c,font="Times 10 bold")
            l2.grid(row=2,column=0)
            b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
            b1.grid(row=4,column=0)
    if d=="Double":
        a="SELECT Occupancy from Two WHERE Number=%s"
        con.execute(a,(e,))
        k=con.fetchall()
        if k==[('Vacant',)]:
            if (int(e)>=10 and int(e)<=19):
                dow=Tk()
                dow.geometry("350x300")
                cost=3000
                l1=Label(dow,text="Cost of each room:-",font="Arial 10 bold")
                l2=Label(dow,text="Days of stay:-",font="Arial 10 bold")
                l3=Label(dow,text="Central Goods and Service Tax(CGST):-",font="Arial 10 bold")
                l4=Label(dow,text="State Goods and Service Tax(SGST):-",font="Arial 10 bold")
                l5=Label(dow,text="Total Payable Amount:-",font="Arial 10 bold")
                l6=Label(dow,text=datetime.now().time(),font="Arial 8 bold")
                l7=Label(dow,text=datetime.now().date(),font="Arial 8 bold")
                am=int(f)*3000
                gst=2*(0.18)*3000
                amount=am+gst
                e1=Label(dow,text="3000",font="none 8 bold")
                e2=Label(dow,text=int(f),font="none 8 bold")
                e3=Label(dow,text="18%",font="none 8 bold")
                e4=Label(dow,text="18%",font="none 8 bold")
                e5=Label(dow,text=amount,font="none 8 bold")
                l6.grid(row=0,column=0,padx=5,pady=5)
                l7.grid(row=0,column=1,padx=5,pady=5)
                l1.grid(row=1,column=0,padx=5,pady=5,sticky=W)
                e1.grid(row=1,column=1,padx=5,pady=5,sticky=E)
                l2.grid(row=4,column=0,padx=5,pady=5,sticky=W)
                e2.grid(row=4,column=1,padx=5,pady=5,sticky=E)
                l3.grid(row=8,column=0,padx=5,pady=5,sticky=W)
                e3.grid(row=8,column=1,padx=5,pady=5,sticky=E)
                l4.grid(row=12,column=0,padx=5,pady=5,sticky=W)
                e4.grid(row=12,column=1,padx=5,pady=5,sticky=E)
                l5.grid(row=16,column=0,padx=5,pady=5,sticky=W)
                e5.grid(row=16,column=1,padx=5,pady=5,sticky=E)
                b1=Button(dow,text="Proceed to Pay",command=Pay,font="Arial",bg="#add8e6")
                b2=Button(dow,text="Cancel",command=dow.destroy,font="Arial",bg="#add8e6")
                b1.grid(row=20,column=0,padx=5,pady=5,sticky=W)
                b2.grid(row=20,column=1,padx=5,pady=5,sticky=E)
            else:
                cow=Tk()
                cow.geometry("250x100")
                l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
                l1.grid(row=0,column=0)
                b="SELECT Number FROM Two WHERE Occupancy='Vacant'"
                con.execute(b)
                c=con.fetchall()
                l2=Label(cow,text=c,font="Times 10 bold")
                l2.grid(row=2,column=0)
                b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
                b1.grid(row=4,column=0)
        else:
            cow=Tk()
            cow.geometry("250x100")
            l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
            l1.grid(row=0,column=0)
            b="SELECT Number FROM Two WHERE Occupancy='Vacant'"
            con.execute(b)
            c=con.fetchall()
            l2=Label(cow,text=c,font="Times 10 bold")
            l2.grid(row=2,column=0)
            b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
            b1.grid(row=4,column=0)
    if d=="Triple":
        a="SELECT Occupancy from three WHERE Number=%s"
        con.execute(a,(e,))
        k=con.fetchall()
        if k==[('Vacant',)]:
            if (int(e)>=20 and int(e)<=30):
                dow=Tk()
                dow.geometry("350x300")
                cost=3500
                l1=Label(dow,text="Cost of each room:-",font="Arial 10 bold")
                l2=Label(dow,text="Days of stay:-",font="Arial 10 bold")
                l3=Label(dow,text="Central Goods and Service Tax(CGST):-",font="Arial 10 bold")
                l4=Label(dow,text="State Goods and Service Tax(SGST):-",font="Arial 10 bold")
                l5=Label(dow,text="Total Payable Amount:-",font="Arial 10 bold")
                l6=Label(dow,text=datetime.now().time(),font="Arial 8 bold")
                l7=Label(dow,text=datetime.now().date(),font="Arial 8 bold")
                am=int(f)*3500
                gst=2*(0.18)*3500
                amount=am+gst
                e1=Label(dow,text="3500",font="none 8 bold")
                e2=Label(dow,text=int(f),font="none 8 bold")
                e3=Label(dow,text="18%",font="none 8 bold")
                e4=Label(dow,text="18%",font="none 8 bold")
                e5=Label(dow,text=amount,font="none 8 bold")
                l6.grid(row=0,column=0,padx=5,pady=5)
                l7.grid(row=0,column=1,padx=5,pady=5)
                l1.grid(row=1,column=0,padx=5,pady=5,sticky=W)
                e1.grid(row=1,column=1,padx=5,pady=5,sticky=E)
                l2.grid(row=4,column=0,padx=5,pady=5,sticky=W)
                e2.grid(row=4,column=1,padx=5,pady=5,sticky=E)
                l3.grid(row=8,column=0,padx=5,pady=5,sticky=W)
                e3.grid(row=8,column=1,padx=5,pady=5,sticky=E)
                l4.grid(row=12,column=0,padx=5,pady=5,sticky=W)
                e4.grid(row=12,column=1,padx=5,pady=5,sticky=E)
                l5.grid(row=16,column=0,padx=5,pady=5,sticky=W)
                e5.grid(row=16,column=1,padx=5,pady=5,sticky=E)
                b1=Button(dow,text="Proceed to Pay",command=Pay,font="Arial",bg="#add8e6")
                b2=Button(dow,text="Cancel",command=dow.destroy,font="Arial",bg="#add8e6")
                b1.grid(row=20,column=0,padx=5,pady=5,sticky=W)
                b2.grid(row=20,column=1,padx=5,pady=5,sticky=E)
            else:
                cow=Tk()
                cow.geometry("250x100")
                l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
                l1.grid(row=0,column=0)
                b="SELECT Number FROM Three WHERE Occupancy='Vacant'"
                con.execute(b)
                c=con.fetchall()
                l2=Label(cow,text=c,font="Times 10 bold")
                l2.grid(row=2,column=0)
                b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
                b1.grid(row=4,column=0)
        else:
            cow=Tk()
            cow.geometry("250x100")
            l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
            l1.grid(row=0,column=0)
            b="SELECT Number FROM Three WHERE Occupancy='Vacant'"
            con.execute(b)
            c=con.fetchall()
            l2=Label(cow,text=c,font="Times 10 bold")
            l2.grid(row=2,column=0)
            b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
            b1.grid(row=4,column=0)
    if d=="Queen":
        a="SELECT Occupancy from queen WHERE Number=%s"
        con.execute(a,(e,))
        k=con.fetchall()
        if k==[('Vacant',)]:
            if (int(e)>=31 and int(e)<=40):
                dow=Tk()
                dow.geometry("350x300")
                cost=4000
                l1=Label(dow,text="Cost of each room:-",font="Arial 10 bold")
                l2=Label(dow,text="Days of stay:-",font="Arial 10 bold")
                l3=Label(dow,text="Central Goods and Service Tax(CGST):-",font="Arial 10 bold")
                l4=Label(dow,text="State Goods and Service Tax(SGST):-",font="Arial 10 bold")
                l5=Label(dow,text="Total Payable Amount:-",font="Arial 10 bold")
                l6=Label(dow,text=datetime.now().time(),font="Arial 8 bold")
                l7=Label(dow,text=datetime.now().date(),font="Arial 8 bold")
                am=int(f)*4000
                gst=2*(0.18)*4000
                amount=am+gst
                e1=Label(dow,text="4000",font="none 8 bold")
                e2=Label(dow,text=int(f),font="none 8 bold")
                e3=Label(dow,text="18%",font="none 8 bold")
                e4=Label(dow,text="18%",font="none 8 bold")
                e5=Label(dow,text=amount,font="none 8 bold")
                l6.grid(row=0,column=0,padx=5,pady=5)
                l7.grid(row=0,column=1,padx=5,pady=5)
                l1.grid(row=1,column=0,padx=5,pady=5,sticky=W)
                e1.grid(row=1,column=1,padx=5,pady=5,sticky=E)
                l2.grid(row=4,column=0,padx=5,pady=5,sticky=W)
                e2.grid(row=4,column=1,padx=5,pady=5,sticky=E)
                l3.grid(row=8,column=0,padx=5,pady=5,sticky=W)
                e3.grid(row=8,column=1,padx=5,pady=5,sticky=E)
                l4.grid(row=12,column=0,padx=5,pady=5,sticky=W)
                e4.grid(row=12,column=1,padx=5,pady=5,sticky=E)
                l5.grid(row=16,column=0,padx=5,pady=5,sticky=W)
                e5.grid(row=16,column=1,padx=5,pady=5,sticky=E)
                b1=Button(dow,text="Proceed to Pay",command=Pay,font="Arial",bg="#add8e6")
                b2=Button(dow,text="Cancel",command=dow.destroy,font="Arial",bg="#add8e6")
                b1.grid(row=20,column=0,padx=5,pady=5,sticky=W)
                b2.grid(row=20,column=1,padx=5,pady=5,sticky=E)
            else:
                cow=Tk()
                cow.geometry("250x100")
                l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
                l1.grid(row=0,column=0)
                b="SELECT Number FROM queen WHERE Occupancy='Vacant'"
                con.execute(b)
                c=con.fetchall()
                l2=Label(cow,text=c,font="Times 10 bold")
                l2.grid(row=2,column=0)
                b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
                b1.grid(row=4,column=0)
        else:
            cow=Tk()
            cow.geometry("250x100")
            l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
            l1.grid(row=0,column=0)
            b="SELECT Number FROM queen WHERE Occupancy='Vacant'"
            con.execute(b)
            c=con.fetchall()
            l2=Label(cow,text=c,font="Times 10 bold")
            l2.grid(row=2,column=0)
            b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
            b1.grid(row=4,column=0)
    if d=="Suite":
        a="SELECT Occupancy from suite WHERE Number=%s"
        con.execute(a,(e,))
        k=con.fetchall()
        if k==[('Vacant',)]:
            if (int(e)>=41 and int(e)<=45):
                dow=Tk()
                dow.geometry("350x300")
                cost=5000
                l1=Label(dow,text="Cost of each room:-",font="Arial 10 bold")
                l2=Label(dow,text="Days of stay:-",font="Arial 10 bold")
                l3=Label(dow,text="Central Goods and Service Tax(CGST):-",font="Arial 10 bold")
                l4=Label(dow,text="State Goods and Service Tax(SGST):-",font="Arial 10 bold")
                l5=Label(dow,text="Total Payable Amount:-",font="Arial 10 bold")
                l6=Label(dow,text=datetime.now().time(),font="Arial 8 bold")
                l7=Label(dow,text=datetime.now().date(),font="Arial 8 bold")
                am=int(f)*5000
                gst=2*(0.18)*5000
                amount=am+gst
                e1=Label(dow,text="5000",font="none 8 bold")
                e2=Label(dow,text=int(f),font="none 8 bold")
                e3=Label(dow,text="18%",font="none 8 bold")
                e4=Label(dow,text="18%",font="none 8 bold")
                e5=Label(dow,text=amount,font="none 8 bold")
                l6.grid(row=0,column=0,padx=5,pady=5)
                l7.grid(row=0,column=1,padx=5,pady=5)
                l1.grid(row=1,column=0,padx=5,pady=5,sticky=W)
                e1.grid(row=1,column=1,padx=5,pady=5,sticky=E)
                l2.grid(row=4,column=0,padx=5,pady=5,sticky=W)
                e2.grid(row=4,column=1,padx=5,pady=5,sticky=E)
                l3.grid(row=8,column=0,padx=5,pady=5,sticky=W)
                e3.grid(row=8,column=1,padx=5,pady=5,sticky=E)
                l4.grid(row=12,column=0,padx=5,pady=5,sticky=W)
                e4.grid(row=12,column=1,padx=5,pady=5,sticky=E)
                l5.grid(row=16,column=0,padx=5,pady=5,sticky=W)
                e5.grid(row=16,column=1,padx=5,pady=5,sticky=E)
                b1=Button(dow,text="Proceed to Pay",command=Pay,font="Arial",bg="#add8e6")
                b2=Button(dow,text="Cancel",command=dow.destroy,font="Arial",bg="#add8e6")
                b1.grid(row=20,column=0,padx=5,pady=5,sticky=W)
                b2.grid(row=20,column=1,padx=5,pady=5,sticky=E)
            else:
                cow=Tk()
                cow.geometry("250x100")
                l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
                l1.grid(row=0,column=0)
                b="SELECT Number FROM Suite WHERE Occupancy='Vacant'"
                con.execute(b)
                c=con.fetchall()
                l2=Label(cow,text=c,font="Times 10 bold")
                l2.grid(row=2,column=0)
                b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
                b1.grid(row=4,column=0)
        else:
            cow=Tk()
            cow.geometry("250x100")
            l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
            l1.grid(row=0,column=0)
            b="SELECT Number FROM suite WHERE Occupancy='Vacant'"
            con.execute(b)
            c=con.fetchall()
            l2=Label(cow,text=c,font="Times 10 bold")
            l2.grid(row=2,column=0)
            b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
            b1.grid(row=4,column=0)
    if d=="President Suite":
        a="SELECT Occupancy from presidentsuite WHERE Number=%s"
        con.execute(a,(e,))
        k=con.fetchall()
        if k==[('Vacant',)]:
            if (int(e)>=46 and int(e)<=48):
                dow=Tk()
                dow.geometry("350x300")
                cost=9000
                l1=Label(dow,text="Cost of each room:-",font="Arial 10 bold")
                l2=Label(dow,text="Days of stay:-",font="Arial 10 bold")
                l3=Label(dow,text="Central Goods and Service Tax(CGST):-",font="Arial 10 bold")
                l4=Label(dow,text="State Goods and Service Tax(SGST):-",font="Arial 10 bold")
                l5=Label(dow,text="Total Payable Amount:-",font="Arial 10 bold")
                l6=Label(dow,text=datetime.now().time(),font="Arial 8 bold")
                l7=Label(dow,text=datetime.now().date(),font="Arial 8 bold")
                am=int(f)*9000
                gst=2*(0.18)*9000
                amount=am+gst
                e1=Label(dow,text="9000",font="none 8 bold")
                e2=Label(dow,text=int(f),font="none 8 bold")
                e3=Label(dow,text="18%",font="none 8 bold")
                e4=Label(dow,text="18%",font="none 8 bold")
                e5=Label(dow,text=amount,font="none 8 bold")
                l6.grid(row=0,column=0,padx=5,pady=5)
                l7.grid(row=0,column=1,padx=5,pady=5)
                l1.grid(row=1,column=0,padx=5,pady=5,sticky=W)
                e1.grid(row=1,column=1,padx=5,pady=5,sticky=E)
                l2.grid(row=4,column=0,padx=5,pady=5,sticky=W)
                e2.grid(row=4,column=1,padx=5,pady=5,sticky=E)
                l3.grid(row=8,column=0,padx=5,pady=5,sticky=W)
                e3.grid(row=8,column=1,padx=5,pady=5,sticky=E)
                l4.grid(row=12,column=0,padx=5,pady=5,sticky=W)
                e4.grid(row=12,column=1,padx=5,pady=5,sticky=E)
                l5.grid(row=16,column=0,padx=5,pady=5,sticky=W)
                e5.grid(row=16,column=1,padx=5,pady=5,sticky=E)
                b1=Button(dow,text="Proceed to Pay",command=Pay,font="Arial",bg="#add8e6")
                b2=Button(dow,text="Cancel",command=dow.destroy,font="Arial",bg="#add8e6")
                b1.grid(row=20,column=0,padx=5,pady=5,sticky=W)
                b2.grid(row=20,column=1,padx=5,pady=5,sticky=E)
            else:
                cow=Tk()
                cow.geometry("250x100")
                l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
                l1.grid(row=0,column=0)
                b="SELECT Number FROM presidentsuite WHERE Occupancy='Vacant'"
                con.execute(b)
                c=con.fetchall()
                l2=Label(cow,text=c,font="Times 10 bold")
                l2.grid(row=2,column=0)
                b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
                b1.grid(row=4,column=0)
        else:
            cow=Tk()
            cow.geometry("250x100")
            l1=Label(cow,text="Check avaiable rooms:-",font="Arial 14 bold")
            l1.grid(row=0,column=0)
            b="SELECT Number FROM presidentsuite WHERE Occupancy='Vacant'"
            con.execute(b)
            c=con.fetchall()
            l2=Label(cow,text=c,font="Times 10 bold")
            l2.grid(row=2,column=0)
            b1=Button(cow, text="Okay",command=cow.destroy,font="Arial 8 bold")
            b1.grid(row=4,column=0)
def Pay():
    win=Tk()
    win.geometry("300x200")
    b1=Button(win,text=("Pay by debit card"),font="Arial 14 bold",command=Book,bg="#add8e6")
    b2=Button(win,text=("Pay by credit card"),font="Arial 14 bold",bg="#add8e6",command=Book)
    b3=Button(win,text=("Pay by net banking"),font="Arial 14 bold",bg="#add8e6",command=Book)
    l1=Label(win,text="Sorry! \nWe are not currently accepting payment on arrival",font="Times 8 bold")
    b1.pack()
    b2.pack()
    b3.pack()
    l1.pack()


box=Tk()
box.title('Waterfall Booking Window')
box.geometry('600x300')
box.configure(background="#add8e6")
l1=Label(box, text="Name:-", font="none 14 bold italic", bg="#ffe5b4")
l2=Label(box, text="Number of people:-", font="none 14 bold italic", bg="#ffe5b4")
l3=Label(box, text="Kind of Room:-", font="none 14 bold italic", bg="#ffe5b4")
l4=Label(box, text="Preferred Room Number:-", font="none 14 bold italic" , bg="#ffe5b4")
l5=Label(box, text="Days of stay", font="none 14 bold italic", bg="#ffe5b4")
l1.grid(row=0, column=0,padx=5,pady=5,sticky=W)
l2.grid(row=1, column=0,padx=5,pady=5,sticky=W)
l3.grid(row=2, column=0,padx=5,pady=5,sticky=W)
l4.grid(row=3, column=0,padx=5,pady=5,sticky=W)
l5.grid(row=4, column=0,padx=5,pady=5,sticky=W)
Name=StringVar()
People=StringVar()
Kind=StringVar()
Preferred=StringVar()
Days=StringVar()
t1=Entry(box, textvariable=Name,font=(14))
t2=Entry(box, textvariable=People,font=(14))
Options=['Single','Double','Triple','Queen','Suite','President Suite']
t3=OptionMenu(box, Kind, *Options)
b3=Button(box, text='Description', command=Description, font=(14))
t4=Entry(box, textvariable=Preferred,font=(14))
t5=Entry(box, textvariable=Days,font=(14))
t1.grid(row=0, column=1,padx=5,pady=5)
t2.grid(row=1, column=1,padx=5,pady=5)
t3.grid(row=2, column=1,padx=5,pady=5)
b3.grid(row=2, column=3, padx=5, pady=5)
t4.grid(row=3, column=1,padx=5,pady=5)
t5.grid(row=4, column=1,padx=5,pady=5)
b1=Button(box, text="Bill", font=(14),command=Billing)
b2=Button(box, text="Cancel",command=box.destroy, font=(14))
b1.grid(row=5, column=0)
b2.grid(row=5, column=1, sticky=E)
mydb=c.connect(host="localhost", user="root", passwd="1234", database="project")
con=mydb.cursor()

    
    

        
